### ISSUE TITLE
Не скачивается dll по ссылке в readme

### ISSUE THREAD

**Issue by TeamBIOS** [Infactum/telegram-native#10]
при открытии любой ссылки [из Latest builds раздела описания](https://github.com/Infactum/telegram-native#latest-builds) проекта ошибка `{"message":"Artifact not found or access denied."}`

**Comment by Infactum** [comment]
Эти ссылки ведут на артефакты CI, которые, к сожалению не хранятся вечно.
Возможно стоило бы сделать релиз, но я уже достаточно давно самостоятельно работоспособность не проверял. А релизить "в слепую" не хочется.

P.S. Конкретно сейчас ссылки живые, но это продлится не слишком долго.
