### ISSUE TITLE
При запуске под пользователем 1С без админских прав, библиотека возвращает ошибку доступа к System32

### ISSUE THREAD

**Issue by TeamBIOS** [Infactum/telegram-native#9]
Подключили библиотеку в 1С НаСервере и при наличии прав администратора пользователя 1С Windows всё работает нормально, а под обычным пользователем выдает ошибку: {"@type":"error","code":400,"message":"File \"C:\\Windows\\system32\\td.binlog\" can't be opened/created for reading and writing","@extra":2097306145}
Зачем библиотека хочет сделать запись в системный каталог Windows? И есть ли возможность как-то работать с библиотекой НаСервере без прав администратора (без записи в каталог system32)?

**Comment by Infactum** [comment]
Это вопрос не столько про компоненту, сколько про [TDLib](https://core.telegram.org/tdlib/docs/#using-json).
Я не смотрел, какая там логика выбора каталогов для логов и в какой момент файл инициируется.
Ошибку прямо сразу после подключения компоненты выдает, или после отправки запроса? В последнем случае можно изменить каталог логов через соответствующий метод.
А если сразу - то разбираться как определение каталога реализовано в библиотеке телеграмм. Возможно оно там не очень корректно работает из-за того, что сервер 1С у вас под служебным пользователем без домашнего каталога крутится.

**Comment by TeamBIOS** [comment]
Спасибо, действительно не прописали пути для библиотеки и она выбирала системные.
